export const cytoscopeElementsData = {
  nodes: [
    {
      group: 'nodes',
      data: {
        id: 844424930131969,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Andr...',
          title: 'Developer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131969,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Andr...',
          title: 'Developer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131969,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Andr...',
          title: 'Developer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131969,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Andr...',
          title: 'Developer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131971,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Alic...',
          title: 'Engineer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131971,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Alic...',
          title: 'Engineer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131972,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Bob',
          title: 'Analyst',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131972,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Bob',
          title: 'Analyst',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131973,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Char...',
          title: 'Designer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131973,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Char...',
          title: 'Designer',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131974,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Davi...',
          title: 'Manager',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131974,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Davi...',
          title: 'Manager',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131975,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Eva',
          title: 'Architect',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131975,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Eva',
          title: 'Architect',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131976,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Fran...',
          title: 'Consultant',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131976,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Fran...',
          title: 'Consultant',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131977,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Grac...',
          title: 'Coordinator',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131977,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Grac...',
          title: 'Coordinator',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131978,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Henr...',
          title: 'Specialist',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131978,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Henr...',
          title: 'Specialist',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131979,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Ivy',
          title: 'Administrator',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131979,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Ivy',
          title: 'Administrator',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131971,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Alic...',
          title: 'Engineer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131971,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Alic...',
          title: 'Engineer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131972,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Bob',
          title: 'Analyst',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131972,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Bob',
          title: 'Analyst',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131973,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Char...',
          title: 'Designer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131973,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Char...',
          title: 'Designer',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131974,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Davi...',
          title: 'Manager',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131974,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Davi...',
          title: 'Manager',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131975,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Eva',
          title: 'Architect',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131975,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Eva',
          title: 'Architect',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131976,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Fran...',
          title: 'Consultant',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131976,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Fran...',
          title: 'Consultant',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131977,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Grac...',
          title: 'Coordinator',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131977,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Grac...',
          title: 'Coordinator',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131978,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Henr...',
          title: 'Specialist',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131978,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Henr...',
          title: 'Specialist',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131979,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Ivy',
          title: 'Administrator',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131979,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Ivy',
          title: 'Administrator',
        },
        caption: 'name',
      },
      alias: 'v',
      classes: 'node',
    },
    {
      group: 'nodes',
      data: {
        id: 844424930131970,
        label: 'Person',
        backgroundColor: '#7535E5',
        borderColor: '#EB2728',
        fontColor: '#FFF',
        size: 55,
        properties: {
          name: 'Kaml...',
          title: 'Tester',
        },
        caption: 'name',
      },
      alias: 'v2',
      classes: 'node',
    },
  ],
  edges: [
    {
      group: 'edges',
      data: {
        id: 1125899906842625,
        source: 844424930131970,
        target: 844424930131969,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842636,
        source: 844424930131970,
        target: 844424930131969,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842625,
        source: 844424930131970,
        target: 844424930131969,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842636,
        source: 844424930131970,
        target: 844424930131969,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842626,
        source: 844424930131970,
        target: 844424930131970,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842637,
        source: 844424930131970,
        target: 844424930131970,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842627,
        source: 844424930131970,
        target: 844424930131971,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842638,
        source: 844424930131970,
        target: 844424930131971,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842628,
        source: 844424930131970,
        target: 844424930131972,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842639,
        source: 844424930131970,
        target: 844424930131972,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842629,
        source: 844424930131970,
        target: 844424930131973,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842640,
        source: 844424930131970,
        target: 844424930131973,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842630,
        source: 844424930131970,
        target: 844424930131974,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842641,
        source: 844424930131970,
        target: 844424930131974,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842631,
        source: 844424930131970,
        target: 844424930131975,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842642,
        source: 844424930131970,
        target: 844424930131975,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842632,
        source: 844424930131970,
        target: 844424930131976,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842643,
        source: 844424930131970,
        target: 844424930131976,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842633,
        source: 844424930131970,
        target: 844424930131977,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842644,
        source: 844424930131970,
        target: 844424930131977,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842634,
        source: 844424930131970,
        target: 844424930131978,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842645,
        source: 844424930131970,
        target: 844424930131978,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842635,
        source: 844424930131970,
        target: 844424930131979,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842646,
        source: 844424930131970,
        target: 844424930131979,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842627,
        source: 844424930131970,
        target: 844424930131971,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842638,
        source: 844424930131970,
        target: 844424930131971,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842628,
        source: 844424930131970,
        target: 844424930131972,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842639,
        source: 844424930131970,
        target: 844424930131972,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842629,
        source: 844424930131970,
        target: 844424930131973,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842640,
        source: 844424930131970,
        target: 844424930131973,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842630,
        source: 844424930131970,
        target: 844424930131974,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842641,
        source: 844424930131970,
        target: 844424930131974,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842631,
        source: 844424930131970,
        target: 844424930131975,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842642,
        source: 844424930131970,
        target: 844424930131975,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842632,
        source: 844424930131970,
        target: 844424930131976,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842643,
        source: 844424930131970,
        target: 844424930131976,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842633,
        source: 844424930131970,
        target: 844424930131977,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842644,
        source: 844424930131970,
        target: 844424930131977,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842634,
        source: 844424930131970,
        target: 844424930131978,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842645,
        source: 844424930131970,
        target: 844424930131978,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842635,
        source: 844424930131970,
        target: 844424930131979,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
    {
      group: 'edges',
      data: {
        id: 1125899906842646,
        source: 844424930131970,
        target: 844424930131979,
        label: 'RELTYPE',
        backgroundColor: '#F16667',
        borderColor: '#EB2728',
        fontColor: '#2A2C34',
        size: 1,
        properties: {},
        caption: 'label',
      },
      alias: 'r',
      classes: 'edge',
    },
  ],
};
